name: container 

on: push

jobs:
  docker-containers:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: log node version 
        run: |
          node -v 
          npm -v
          cat /etc/os-release
