name: matrix 

on: [push]

jobs:
  node-playground:
    strategy:
      matrix: 
        node_version: [8,6,7]
        os: ["ubuntu-latest", "window-latest", "macos-latest"]
      fail-fast: true
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node version
        run: node -v 


