name: my first git actions commands

on: [push] 

jobs:
  run-my-steps-here:
    runs-on: ubuntu-22.04
    steps:
      - name: list the releases
        run:  ls /etc/*release
      - name: name the releases
        run: cat /etc/os-release
      - name: multiline shell commands
        run: |
          node -v
          npm -v
      - name: run python 
        run: |
          import platform 
          print (platform.processor())
        shell: |
          python





