name: my first git actions commands

on: [push] 

jobs:
  run-my-steps:
    runs-on: ubuntu-22.04
    steps:
      - name: echo the relaese name
        run:  echo /etc/os-release
      - name: multiline shell commands
        run: |
          node -v
          npm -v





